on:
  push:
    branches:
      - master
  pull_request:

name: CI

jobs:
  test:
    name: run tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '^1.13.0'
      - name: Run tests
        run: go test

  fmt:
    name: check code formatting with gofmt
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '^1.13.0'
      - name: run gofmt
        run: diff -u <(echo -n) <(gofmt -d ./)
